apiVersion: batch/v1
kind: CronJob
metadata:
  name: chat-job
  labels:
    job-name: chat-job
spec:
  schedule: "* 1 * * *"  # Default: run every 1 hour
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: chat-client
            image: registry.redhat.io/openshift4/ose-tools-rhel8:latest
            command: ["/bin/sh", "/script/chat-script.sh"]
            env:
            - name: VLLM_URL
              value: "http://granite-33-2b-instruct-predictor.model-as-a-service.svc.cluster.local"
            - name: MODEL_NAME
              value: "granite-33-2b-instruct"
            - name: PROMPT_TEXT
              value: "What is the capital of France?"
            - name: NUM_REQUESTS
              value: "50"
            - name: SLEEP_BETWEEN_REQUESTS
              value: "3"
            - name: MAX_TOKENS
              value: "100"
            - name: TEMPERATURE
              value: "0.7"
            volumeMounts:
            - name: script-volume
              mountPath: /script
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: chat-script
              defaultMode: 0777  # Make the script executable
